#!/usr/bin/env bash
qmk_dir="$1"
legends="$2"
usr_spc="$qmk_dir/users/jbarr21"
qmk json2c "$usr_spc/keymaps/cantor.json" -o /tmp/keymap.c
sed -i '' '/include/d' /tmp/keymap.c
gcc -E -include "$usr_spc/layout.h" -DKEYMAP_DISPLAY /tmp/keymap.c > /tmp/keymap2.c
mv /tmp/keymap2.c /tmp/keymap.c
keymapviz -t fancy -k crkbd -c "$legends" /tmp/keymap.c \
    | sed 's| *generated by \[keymapviz\] \*||g'