name: Build personal keymaps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  render:
    uses: jbarr21/keymap-display/.github/workflows/render-keymap.yml@main
    with:
      keymap_type: qmk
      output_type: kd
      keymap_path: layout.h
      keymap_json_path: keymaps/keymap.json

  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - cantor
          - corne
          - moonlander
          - piantor
          - piantor_pro
          - sweeeeep
          - bm16s
    steps:
    - name: Disable git safe directory checks
      run: git config --global --add safe.directory '*'
    - name: Checkout QMK/QMK
      if: matrix.keyboard != 'moonlander'
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        ref: 0.22.14
        persist-credentials: false
        submodules: recursive
    - name: Checkout ZSA/QMK
      if: matrix.keyboard == 'moonlander'
      uses: actions/checkout@v3
      with:
        repository: zsa/qmk_firmware
        ref: 2f50d1ed03058f69d7aeddaae34eb07673f3f9e8 # firmware22
        persist-credentials: false
        submodules: recursive
    - name: Checkout Beekeeb/QMK
      if: matrix.keyboard == 'piantor_pro'
      uses: actions/checkout@v3
      with:
        repository: beekeeb/vial-qmk-piantor-pro
        path: 'qmk_firmware_bk'
        ref: 5b6e44c2f5575e96b8c6d3c63b8fa6bd3f7283ac # 2/27/24
        persist-credentials: false
        submodules: recursive
    - name: Checkout Fingerpunch/QMK
      if: matrix.keyboard == 'sweeeeep'
      uses: actions/checkout@v3
      with:
        repository: jbarr21/qmk_firmware
        path: 'qmk_firmware_fp'
        ref: fp/a01533e3/may2023 # 3/11/23
        persist-credentials: false
        submodules: recursive
    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}
        persist-credentials: false
    - name: Symlink beekeeb boards
      if: matrix.keyboard == 'piantor_pro'
      run: ln -s $GITHUB_WORKSPACE/qmk_firmware_bk/keyboards/beekeeb/piantor_pro keyboards/beekeeb/piantor_pro
    - name: Symlink fingerpunch boards
      if: matrix.keyboard == 'sweeeeep'
      run: ln -s $GITHUB_WORKSPACE/qmk_firmware_fp/keyboards/fingerpunch keyboards/fingerpunch
    - name: Install qmk_cli deps
      run: python3 -m pip install -r requirements.txt
    - name: Build firmware
      run: qmk compile -c "users/${{ github.actor }}/keymaps/${{ matrix.keyboard }}.json"
    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.actor }}_firmware
        path: |
          *.bin
          *.hex
          *.uf2
        retention-days: 7
