name: Build personal keymaps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: nanasess/setup-chromedriver@v1
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '88.0.4324.96'
    - name: Launch browser
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Prepare Selenium
      uses: nanasess/setup-chromedriver@master
    - name: Download image
      run: pipenv run python qmk2kle.py -l -i layout.h
    - name: Upload image
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.actor }}-keyboard-layout.png
        path: |
          *.png
        retention-days: 7
    - name: Commit updated image
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[Skip CI] Automated keymap render"
        file_pattern: keyboard-layout.png

  Build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - cantor
          - corne
          - moonlander
          - bm16s
    steps:
    - name: Checkout QMK/QMK
      if: matrix.keyboard != 'moonlander'
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        ref: master
        persist-credentials: false
        submodules: recursive
    - name: Checkout ZSA/QMK
      if: matrix.keyboard == 'moonlander'
      uses: actions/checkout@v2
      with:
        repository: zsa/qmk_firmware
        ref: firmware21
        persist-credentials: false
        submodules: recursive
    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}
        persist-credentials: false
    - name: Build firmware
      run: qmk compile -c "users/${{ github.actor }}/keymaps/${{ matrix.keyboard }}.json"
    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.actor }}_firmware
        path: |
          *.bin
          *.hex
        retention-days: 7