name: Build personal keymaps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  render:
    uses: jbarr21/keymap-display/.github/workflows/render-keymap.yml@main
    with:
      keymap_type: qmk
      output_type: kd
      keymap_path: layout.h
      keymap_json_path: keymaps/keymap.json

  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - cantor
          - corne
          - moonlander
          - piantor
          - sweeeeep
          - bm16s
    steps:
    - name: Disable git safe directory checks
      run: git config --global --add safe.directory '*'
    - name: Checkout QMK/QMK
      if: matrix.keyboard != 'moonlander'
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        ref: 0.19.12
        persist-credentials: false
        submodules: recursive
    - name: Checkout ZSA/QMK
      if: matrix.keyboard == 'moonlander'
      uses: actions/checkout@v3
      with:
        repository: zsa/qmk_firmware
        ref: firmware23
        persist-credentials: false
        submodules: recursive
    - name: Checkout Fingerpunch/QMK
      if: matrix.keyboard == 'sweeeeep'
      uses: actions/checkout@v3
      with:
        repository: sadekbaroudi/qmk_firmware
        path: 'qmk_firmware_fp'
        ref: 822057fd447996f08c00449d56220d720cc728ff
        persist-credentials: false
        submodules: recursive
    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}
        persist-credentials: false
    - name: Symlink fingerpunch boards
      if: matrix.keyboard == 'sweeeeep'
      run: ln -s $GITHUB_WORKSPACE/qmk_firmware_fp/keyboards/fingerpunch keyboards/fingerpunch
    - name: Build firmware
      run: qmk compile -c "users/${{ github.actor }}/keymaps/${{ matrix.keyboard }}.json"
    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.actor }}_firmware
        path: |
          *.bin
          *.hex
          *.uf2
        retention-days: 7
