name: Build personal keymaps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - corne
          - moonlander
          - bm16s
    steps:
    - name: Checkout QMK/QMK
      if: matrix.keyboard != 'moonlander'
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        persist-credentials: false
        submodules: recursive
    - name: Checkout ZSA/QMK
      if: matrix.keyboard == 'moonlander'
      uses: actions/checkout@v2
      with:
        repository: zsa/qmk_firmware
        persist-credentials: false
        submodules: recursive
    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}
        persist-credentials: false
    - name: Build firmware
      run: qmk compile -c "users/${{ github.actor }}/keymaps/${{ matrix.keyboard }}.json"
    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.actor }}_firmware
        path: |
          *.bin
          *.hex
        retention-days: 7